# syntax=docker/dockerfile:1

FROM node:22-alpine AS base
WORKDIR /app

FROM base AS deps
COPY package.json package-lock.json ./
RUN npm ci

# ── dev : vite dev server, source montée en volume, hot-reload ───────────
FROM deps AS dev
COPY . .
EXPOSE 5174
CMD ["npm", "run", "dev"]

# ── build : bundle statique pour la prod ──────────────────────────────────
# Les variables VITE_* sont figées dans le bundle au build, pas au runtime :
# on les reçoit en build args (fournis par docker-compose depuis le .env
# racine) et on les réécrit dans .env.production pour que Vite les charge.
FROM deps AS build
ARG VITE_THREADS_E2EE_KEY
ARG VITE_LIVEKIT_E2EE_KEY
ARG VITE_LIVEKIT_URL
ARG VITE_PEER_HOST
ARG VITE_PEER_PORT
ARG VITE_PEER_SECURE
ARG VITE_PEER_PATH
ARG VITE_PEER_PUBLISHABLE_KEY
ARG VITE_KEYCLOAK_URL
ARG VITE_KEYCLOAK_REALM
ARG VITE_KEYCLOAK_CLIENT_ID
ARG VITE_SOCKET_URL
ARG VITE_SOCKET_PATH
ARG VITE_API_URL
ARG VITE_DEV
ARG VITE_USE_HTTPS
ARG VITE_TAURI_DEV_IP
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_FIREBASE_MEASUREMENT_ID
ARG VITE_FIREBASE_VAPID_KEY
ENV VITE_THREADS_E2EE_KEY=$VITE_THREADS_E2EE_KEY \
    VITE_LIVEKIT_E2EE_KEY=$VITE_LIVEKIT_E2EE_KEY \
    VITE_LIVEKIT_URL=$VITE_LIVEKIT_URL \
    VITE_PEER_HOST=$VITE_PEER_HOST \
    VITE_PEER_PORT=$VITE_PEER_PORT \
    VITE_PEER_SECURE=$VITE_PEER_SECURE \
    VITE_PEER_PATH=$VITE_PEER_PATH \
    VITE_PEER_PUBLISHABLE_KEY=$VITE_PEER_PUBLISHABLE_KEY \
    VITE_KEYCLOAK_URL=$VITE_KEYCLOAK_URL \
    VITE_KEYCLOAK_REALM=$VITE_KEYCLOAK_REALM \
    VITE_KEYCLOAK_CLIENT_ID=$VITE_KEYCLOAK_CLIENT_ID \
    VITE_SOCKET_URL=$VITE_SOCKET_URL \
    VITE_SOCKET_PATH=$VITE_SOCKET_PATH \
    VITE_API_URL=$VITE_API_URL \
    VITE_DEV=$VITE_DEV \
    VITE_USE_HTTPS=$VITE_USE_HTTPS \
    VITE_TAURI_DEV_IP=$VITE_TAURI_DEV_IP \
    VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY \
    VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN \
    VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID \
    VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET \
    VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID \
    VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID \
    VITE_FIREBASE_MEASUREMENT_ID=$VITE_FIREBASE_MEASUREMENT_ID \
    VITE_FIREBASE_VAPID_KEY=$VITE_FIREBASE_VAPID_KEY
COPY . .
RUN printenv | grep '^VITE_' > .env.production
RUN npm run build

# ── prod : nginx sert le bundle statique ──────────────────────────────────
FROM nginx:alpine AS prod
COPY --from=build /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
