declare module '@tauri-apps/plugin-shell';
declare module '@tauri-apps/plugin-deep-link';
declare module '@tauri-apps/api/event';
declare module '@tauri-apps/plugin-notification';
declare module '@tauri-apps/api/window';
declare module 'drag-drop-touch';
declare module '@onlyoffice/document-editor-vue';
declare module '@guolao/vue-monaco-editor';
declare module 'monaco-editor';
