name: Build Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Installation des dépendances
        run: bun install

      - name: Vérification du Build
        run: bun run build
